services:
  # PostgreSQL Database
  - type: pserv
    name: nft-minting-db
    env: docker
    plan: free
    region: oregon
    property: postgresql
    disk:
      name: nft-minting-db-disk
      size: 1
    ipAllowList: []

  # Django Backend Service
  - type: web
    name: nft-minting-backend
    env: python3
    region: oregon
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: |
      cd backend
      gunicorn nft_backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: nft-minting-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: nft-minting-backend.onrender.com,localhost,127.0.0.1
      - key: RENDER
        value: true
      - key: FILEBASE_ACCESS_KEY
        sync: false
      - key: FILEBASE_SECRET_KEY
        sync: false
      - key: FILEBASE_BUCKET_NAME
        value: nft-minting-bucket
