# Generated by Django 4.2.7 on 2025-07-04 02:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFTCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('symbol', models.CharField(blank=True, max_length=10)),
                ('contract_address', models.CharField(blank=True, max_length=42)),
                ('creator', models.CharField(max_length=42)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NFTMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_ipfs_hash', models.CharField(max_length=100)),
                ('image_ipfs_url', models.URLField()),
                ('metadata_ipfs_hash', models.CharField(max_length=100)),
                ('metadata_ipfs_url', models.URLField()),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('contract_address', models.CharField(blank=True, max_length=42)),
                ('owner_address', models.CharField(max_length=42)),
                ('minted_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=66)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfts.nftcollection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('upload_status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('bytes_uploaded', models.BigIntegerField(default=0)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nft_metadata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nfts.nftmetadata')),
            ],
        ),
        migrations.CreateModel(
            name='NFTAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_type', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('display_type', models.CharField(blank=True, max_length=50)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='nfts.nftmetadata')),
            ],
        ),
    ]
